### ISSUE TITLE
Help too big file size 

### ISSUE THREAD

**Issue by sdhtele** [mohdsabahat/sub-muxer#10]
how to make the results of the bot file not too big sir ?

**Comment by godseye439** [comment]
Try changing the preset [here](https://github.com/mohdsabahat/sub-muxer/blob/4a180ce8c6bea66951582032a4a16ad569ea68c4/helper_func/mux.py#L114), A slower preset will provide better compression.

These are the presets u can change into:
ultrafast
superfast
veryfast
faster
fast
medium
slow
slower
veryslow

**Comment by mohdsabahat** [comment]
> how to make the results of the bot file not too big sir ?

The bot currently uses ultrafast preset (recommended to use on heroku)..
Which can be changed to other values as mentioned by @godseye439 .. doing so would reduce the file size comparatively and as well as give a better compression..
But Heroku's free tier might not be able to handle the process and you might run into "R12" error in heroku logs, in which case you would need to use a higher tier or deploy it to a VPS or something with good system specs!
