### ISSUE TITLE
[Feature Request]: Making the file we give as the only text stream present in output file

### ISSUE THREAD

**Issue by Athena1433** [mohdsabahat/sub-muxer#3]
Currently the bot makes the subtitle file we give as the Default stream, keeping the rest of the stream as it is. please make it so that it removes the other text streams and just outputs the file only with the subtitle we've given just like [this](https://t.me/muxed_bot) bot works. It'll be really helpful if u consider this. Thank You

**Comment by mohdsabahat** [comment]
Reviewing and testing the  PR will take some time..
Alternatively you can deploy using **[extra](https://github.com/mohdsabahat/sub-muxer/tree/extra)** branch.
Any bugs identified can reported by opening an issue.
